# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XmAS5-ljTSuMh83M34jot4WjxAc3M2md
"""

from google.colab import files
files.upload()

!mkdir ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!pip install kaggle

!kaggle datasets download -d msambare/fer2013

import zipfile
zip_ref = zipfile.ZipFile('fer2013.zip','r')
zip_ref.extractall('/content')
zip_ref.close()

train_data_dir = '/content/train'
validation_data_dir = '/content/test'

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
    rescale = 1./255,
    shear_range = 0.3,
    zoom_range = 0.3,
    horizontal_flip =True,
    fill_mode='nearest'
)

val_datagen = ImageDataGenerator(rescale=1./255)

train_generators = train_datagen.flow_from_directory(
    train_data_dir,
    color_mode='grayscale',
    target_size = (48, 48),
    batch_size = 32,
    class_mode='categorical',
    shuffle=True
)

val_generators = val_datagen.flow_from_directory(
    validation_data_dir,
    color_mode='grayscale',
    target_size = (48, 48),
    batch_size = 32,
    class_mode='categorical',
    shuffle=True
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPooling2D, Flatten,Dense,Dropout
from tensorflow.keras.layers import BatchNormalization

model = Sequential([
    Conv2D(64, (3,3), activation='relu', input_shape=(48,48,1)),
    BatchNormalization(),
    MaxPooling2D(pool_size=(2,2)),

    Conv2D(128, (3,3), activation='relu'),
    BatchNormalization(),
    MaxPooling2D(pool_size=(2,2)),

    Conv2D(256, (3,3), activation='relu'),
    BatchNormalization(),
    MaxPooling2D(pool_size=(2,2)),

    Flatten(),
    Dense(512, activation='relu'),
    Dropout(0.5),
    Dense(7, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    train_generators,
    validation_data=val_generators,
    epochs=100,
    verbose=1
)

model.save('emotion_detection_model.keras')

from google.colab import files
files.download('emotion_detection_model.keras')

